version: '2'
services:
  jenkins:
    image: (same jenkins image you are using)
    user: (Sudoer user needed)
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - (Files directory):/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
